image: Visual Studio 2017

install:
  - ps: Write-Host "install step"

build_script:
  - ps: Write-Host "This is, like, a build, yo!"
  - ps: Write-Error "This is, like, a build error!"

artifacts:
  - path: '*.bs'